#ifndef STATUS_H
#define STATUS_H

#define UPDATENODE_PROCERROR_START                  2000
#define UPDATENODE_PROCERROR_NO_UPDATES             UPDATENODE_PROCERROR_START + 1
#define UPDATENODE_PROCERROR_WRONG_PARAMETER        UPDATENODE_PROCERROR_START + 2
#define UPDATENODE_PROCERROR_CANCELED               UPDATENODE_PROCERROR_START + 3
#define UPDATENODE_PROCERROR_UPDATE_EXEC_FAILED     UPDATENODE_PROCERROR_START + 4
#define UPDATENODE_PROCERROR_UPDATE_EXEC_CRASHED    UPDATENODE_PROCERROR_START + 5
#define UPDATENODE_PROCERROR_COMMAND_LAUNCH_FAILED  UPDATENODE_PROCERROR_START + 6
#define UPDATENODE_PROCERROR_DOWNLOAD_FAILED        UPDATENODE_PROCERROR_START + 7
#define UPDATENODE_PROCERROR_WINDOWS_UAC_FAILED     UPDATENODE_PROCERROR_START + 8
#define UPDATENODE_PROCERROR_RUN_DOWNLOAD_FIRST     UPDATENODE_PROCERROR_START + 9


#endif // STATUS_H
