#ifndef STATUS_H
#define STATUS_H

#define SARA_PROCERROR_START            2000
#define SARA_PROCERROR_NO_UPDATES       SARA_PROCERROR_START + 1
#define SARA_PROCERROR_WRONG_PARAMETER  SARA_PROCERROR_START + 2


#endif // STATUS_H
