#ifndef STATUS_H
#define STATUS_H

#define UPDATENODE_PROCERROR_START            2000
#define UPDATENODE_PROCERROR_NO_UPDATES       UPDATENODE_PROCERROR_START + 1
#define UPDATENODE_PROCERROR_WRONG_PARAMETER  UPDATENODE_PROCERROR_START + 2


#endif // STATUS_H
